### ISSUE TITLE
Void fluids

### ISSUE THREAD

**Issue by tjsd** [HenryLoenwind/EnderIO#39]
There is no way to void a fluid if  you get too much. Either a block that voids items/fluids or a conduit upgrade with priority enabling would be nice.

**Comment by HenryLoenwind** [comment]
sub-idea for water: "Water Cooker", RF+Water(Fluid)=> Salt (oreDict). Dunno what to do when there's no salt registered.

**Comment by HenryLoenwind** [comment]
implemented in Ender IO Addons version 0.4
